name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次，你可以根据需要调整时间

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork repository
        uses: actions/checkout@v2
        with:
          repository: your-username/Rules
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream repository
        run: git remote add upstream https://github.com/Journalist-HK/Rules.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes to fork repository
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
